# Data
dataset: celeba_256
is_image: true
image_size: 256
center_image: true
image_channels: 3

# Training
snapshot_freq : 10000
snapshot_threshold: 1
log_freq: 5000
eval_freq: 20000
likelihood_threshold: 2000000
likelihood_freq: 50000
fid_freq: 50000
fid_threshold : 1000000
fid_samples_training: 20000
n_eval_batches: 1
n_likelihood_batches: 1
n_warmup_iters: 100000
n_train_iters : 600000
training_batch_size : 96
testing_batch_size: 96

# Autocast
autocast_train: true
autocast_eval : true

# Sampling
sampling_method: ode
sampling_eps: 0.001
denoising: true
# Model
name: ncsnpp
normalization: GroupNorm
nonlinearity : swish
n_channels: 128
ch_mult: 1,1,2,2,2,2,2
attn_resolutions: 16
resamp_with_conv: true
use_fir: false
fir_kernel: 1,3,3,1
skip_rescale : true
resblock_type: biggan
progressive: none
progressive_input: none
progressive_combine: sum
attention_type: ddpm
init_scale: 0.0
fourier_scale: 16
conv_size : 3
embedding_type: positional
mixed_score: true
n_resblocks: 4
ema_rate: 0.9999
numerical_eps: 0.000001

# SDE
sde : cld
beta_type : linear
beta0: 0.1
beta1: 6.9
m_inv: 4.0
gamma: 0.04

# Optimization
optimizer : AdamW
learning_rate: 0.0001
grad_clip : 1.0
dropout: 0.1
weight_decay : 0.01

# Objective
cld_objective: hsm
loss_eps: 0.001
weighting : reweightedv2
checkpoint: checkpoints/celebahq256_600000.pth
device: "cuda:0"
