dataset: "cifar10"
is_image: True
image_size: 32
center_image: True
image_channels: 3
snapshot_freq: 10000
snapshot_threshold: 1
log_freq: 5000
eval_freq: 20000
likelihood_threshold: 2000000
likelihood_freq: 50000
fid_freq: 50000
fid_threshold: 100000
fid_samples_training: 20000
n_eval_batches: 1
n_likelihood_batches: 1
n_warmup_iters: 100000
n_train_iters: 800000
save_freq: 50000
save_threshold: 300000
# Autocast
autocast_train: True
autocast_eval: True
# Sampling
sampling_method: "ode"
sampling_eps: 0.001
denoising: True
name: "ncsnpp"
normalization: "GroupNorm"
nonlinearity: "swish"
n_channels: 128
ch_mult: 1,2,2,2
attn_resolutions: "16"
resamp_with_conv: True
use_fir: True
fir_kernel: 1,3,3,1
skip_rescale : True
resblock_type: "biggan"
progressive: None
progressive_input: "residual"
progressive_combine: "sum"
attention_type: "ddpm"
init_scale: 0.0
fourier_scale: 16
conv_size: 3
embedding_type: fourier
mixed_score: True
n_resblocks: 8
ema_rate: 0.9999
numerical_eps: 0.000000001
sde: "cld"
beta_type: "linear"
beta0: 4.0
beta1: 0.0
m_inv: 4.0
gamma: 0.04
# Optimization
optimizer: "Adam"
learning_rate: 0.0002
grad_clip: 1.0
dropout: 0.1
weight_decay: 0.0
# Objective
cld_objective: "hsm"
loss_eps: 0.00001
weighting: "reweightedv2"
checkpoint: "checkpoints/cifar10_800000.pth"
